version: '3.6'

services:
  gobarber.api:
    image: gobarber-api
    ports: 
      - "5000:5000"
    build:
      context: ./backend/GoBarber.Api
    # networks:
    #   - gobarberApi
    depends_on:
      - sql-server

  sql-server:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Senha@1234"
      ACCEPT_EULA: "Y"
    # networks:
    #   - gobarberApi      

  # gobarber.web:
  #   image: gobarberWeb
  #   ports:
  #     - "80:80"
  #   build:
  #     context: ./frontend/gobarber-web
  #   networks:
  #     - gobarberWeb

networks:
  gobarberApi:
    driver: bridge    