version: '3'

services:
  gobarber.api:
    image: gobarberApi
    ports: 
      - "5000:80"
    build:
      context: ./backend/GoBarber.Api
    networks:
      - gobarberApi
    depends_on:
      - SqlServer

  SqlServer:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Senha@1234"
      ACCEPT_EULA: "Y"

  # gobarber.web:
  #   image: gobarberWeb
  #   ports:
  #     - "80:80"
  #   build:
  #     context: ./frontend/gobarber-web
  #   networks:
  #     - gobarberWeb

networks:
    gobarberApi:
      driver: bridge